name: sp_adapter
description: Screen adaptation. Make UI scale proportionally on different screen sizes.
version: 0.0.1
homepage: https://github.com/Jokergz/sp_adapter
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: